### ISSUE TITLE
vdi_mirror

### ISSUE THREAD

**Issue by leva0887** [terra-farm/terraform-provider-xenserver#18]
Hello, I got new error

xenserver_vdi.vdi: Creating...
  name_label: "" => "test vdi"
  read_only:  "" => "false"
  shared:     "" => "false"
  size:       "" => "1073741824"
  sr_uuid:    "" => "bd5b861e-12b2-8744-ec23-d3b935032344"

Error: Error applying plan:

1 error(s) occurred:

* xenserver_vdi.vdi: 1 error(s) occurred:

* xenserver_vdi.vdi: Unable to parse XenAPI response: got value "vdi_mirror" for enum StorageOperations at SR.get_record -> .allowed_operations[9], but this is not any of the known values

Please help to solve issue

**Comment by mborodin** [comment]
Hi @leva0887,

which version do you use? This issue was resolved few month ago...

**Comment by ringods** [comment]
Stale issue. Closing.
